#ifndef SHL_NUKLEAR_H
#define SHL_NUKLEAR_H

#define NK_INCLUDE_FIXED_TYPE
#define NK_INCLUDE_STANDARD_BOOL
#define NK_INCLUDE_STANDARD_VARARGS
#define NK_INCLUDE_DEFAULT_ALLOCATOR
#include <nuklear.h>

#endif /* SHL_NUKLEAR_H */
